### ISSUE TITLE
Why delete range was marked by do not use?

### ISSUE THREAD

**Issue by guoxiangCN** [pingcap/kvproto#1003]
https://github.com/pingcap/kvproto/blob/e7e21f0e9cd907d6843afbfbd375d39521113db0/proto/kvrpcpb.proto#L443

In our usage scenario, we need to delete the data in the range. However, we see that is labeled with "Do Not Use". Can someone tell me why?

**Comment by disksing** [comment]
I have no idea. I think we can remove the comment.
