### ISSUE TITLE
build failed when use kvproto as a dependency of a project 

### ISSUE THREAD

**Issue by guoxiangCN** [pingcap/kvproto#1013]
looks like 'bytes' was incompatiable

error:
`
|m: &mut ConfChangeV2| { &mut m.context },
     |                                              ^^^^^^^^^^^^^^ expected struct `bytes::bytes::Bytes`, found struct `bytes::Bytes`
     |
     = note: struct `bytes::Bytes` and struct `bytes::bytes::Bytes` have similar names, but are actually distinct types
note: struct `bytes::Bytes` is defined in crate `bytes`
`

cargo tree -d
`shell
bytes v0.4.12
└── protobuf v2.8.0
    ├── grpcio v0.9.1
    │   ├── example03-tikv v0.1.0 (/data/guoxiang/github_projs/rust-examples/example03-tikv)
    │   └── kvproto v0.0.2 (/data/guoxiang/github_projs/kvproto)
    │       └── example03-tikv v0.1.0 (/data/guoxiang/github_projs/rust-examples/example03-tikv)
    ├── grpcio-compiler v0.11.0
    │   └── protobuf-build v0.12.3
    │       [build-dependencies]
    │       ├── kvproto v0.0.2 (/data/guoxiang/github_projs/kvproto) (*)
    │       └── raft-proto v0.6.0
    │           └── kvproto v0.0.2 (/data/guoxiang/github_projs/kvproto) (*)
    ├── kvproto v0.0.2 (/data/guoxiang/github_projs/kvproto) (*)
    ├── protobuf-build v0.12.3 (*)
    ├── protobuf-codegen v2.8.0
    │   └── protobuf-build v0.12.3 (*)
    └── raft-proto v0.6.0 (*)

bytes v1.2.1
└── raft-proto v0.6.0 (*)
`

**Comment by BusyJay** [comment]
Perhaps you should use master version of raft-proto and try again.

**Comment by guoxiangCN** [comment]
It has nothing to do with the latest version of raft-rs aka v0.7.0.

The main reason is that kvproto's protobuf uses v2.8.0 and relies on old bytes_ v0.4.12,
However, the bytes feature of raft-rs is enabled, it relies on 1. x bytes, which is incompatible with the larger versions of the two.

The reason why TiKV works, but other non TiKV projects cannot be compiled is mainly because the path is implemented in TikV
The following path was applied to protobuf v2.8.0:

protobuf = { git = " https://github.com/pingcap/rust-protobuf ", branch = "v2.8" }
protobuf-codegen = { git = " https://github.com/pingcap/rust-protobuf ", branch = "v2.8" }
