### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by xusss** [pingcap/kvproto#102]
Does [here](https://github.com/pingcap/kvproto/blob/master/src/raft_serverpb.rs#L20) need pascal case?
Like:
```rust
use protobuf::Message as MessageImportedForFunctions;
use protobuf::ProtobufEnum as ProtobufEnumImportedForFunctions;
```

**Comment by tiancaiamao** [comment]
hi, @xusss , never mind.
this code is generated by tool, not for reading.
you can read [this file](https://github.com/pingcap/kvproto/blob/master/proto/raft_serverpb.proto) instead.
