### ISSUE TITLE
error: failed to run custom build command for `kvproto v0.0.2

### ISSUE THREAD

**Issue by camilesing** [pingcap/kvproto#1214]
```log
error: failed to run custom build command for `kvproto v0.0.2 (https://github.com/pingcap/kvproto.git?branch=release-6.5#1bdcc25e)`

Caused by:
  process didn't exit successfully: `/Users/camile/Work/opensource/tikv/target/debug/build/kvproto-1400e69117e6ea69/build-script-build` (exit status: 101)
  --- stdout
  `protoc` not in PATH, try using the bundled protoc

  --- stderr
  thread 'main' panicked at 'No suitable `protoc` (>= 3.1.0) found in PATH', /Users/camile/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.13.0/src/protobuf_impl.rs:35:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [build] Error 101
```
![](https://github.com/pingcap/kvproto/assets/11649145/8e4422eb-8f49-436c-9cf5-e87135c35e88)

i want to develop tikv on RustRover. has error on tikv `v6.5.6` when `make build`, i search this repo issue, but still no solution has been found. can a kind-hearted person tell me how to solve this problem? thx
> my env: rustc 1.67.0-nightly, mac of M1

**Comment by disksing** [comment]
It seems that you need to install protocol buffers 3.8.0 first. Make sure `which protoc` can find the binary then you can try again.

**Comment by camilesing** [comment]
> It seems that you need to install protocol buffers 3.8.0 first. Make sure `which protoc` can find the binary then you can try again.

thx, the error report is pass after ` brew install protobuf@3`
