### ISSUE TITLE
Use specific gogo proto version

### ISSUE THREAD

**Issue by overvenus** [pingcap/kvproto#128]
Now, small changes in `.proto` files may lead **huge** changes across all generated `.go` files, and some of them are not even related. I think it is caused by an ambiguous gogo/protobuf generator.

We can use glide to resolved this problem, just like what we've done in [tidb/Makefile](https://github.com/pingcap/tidb/blob/master/Makefile#L13).

cc @siddontang @shenli @ngaut

**Comment by shenli** [comment]
LGTM
