### ISSUE TITLE
Consider an upgrade from proto to cap'nproto

### ISSUE THREAD

**Issue by vRobM** [pingcap/kvproto#222]
http://capnproto.org next gen proto from the protobuf man himself.

**Comment by siddontang** [comment]
Hi @vRobM 

We considered Cap'n Proto before but later we decided to use gRPC.
The proto here is only used for gRPC, can you explain why do you want to do this?

**Comment by vRobM** [comment]
In distributed systems, the amount of back and forth communication is
critical to the ability to have correctness and strong consistency at scale.

The fewer cycles between nodes the better.

Depending what you use gRPC for, Cap'nProto is the more efficient
implementation.


++ Rob

About me <https://remote.com/r>

**Comment by siddontang** [comment]
Yes @vRobM, Cap'n Proto is more efficient than gRPC but we still decide to choose gRPC, maybe with following reasons:

1. We think gRPC is more widely used and more popular, we can easily communicate with TiKV with different programming languages (especially with Go). 
2. We can use TLS directly in gRPC. 
3. We tried Cap'n rust library before but found it was not easy to use. Maybe it is improved a lot so far, but we have already chosen gRPC now.

Another important reason why we can't upgrade Cap'n is that we must upgrade all the user production data or consider a compatibility way to handle gRPC and Cap'n together, this needs lots of work and is not worth to do for us now.

Thank you.

**Comment by Hoverbear** [comment]
It looks like the discussion on this has come to a close. At this time we won't be using Cap'n Proto. If you have further questions feel free to re-open the issue.
