### ISSUE TITLE
Streaming Scan RPC

### ISSUE THREAD

**Issue by rockwotj** [pingcap/kvproto#238]
Is there a reason the Scan RPC isn't streaming?

I'm interested in doing large range scans in TiKV over gRPC, and currently it looks like the only way of doing this is via a repeated scan reusing the end key as the start key and preforming batches of size N.

**Comment by rockwotj** [comment]
cc/ @ryanpbrewster

**Comment by overvenus** [comment]
Hi @rockwotj 

I like the idea! It's not only intuitive but also effective(saves overhead from gRPC). I will forward the issue to TiKV repo where it will have more eyes on the idea.

**Comment by rockwotj** [comment]
Ok I'll close this then.
