### ISSUE TITLE
Generate Wrappers for Prost protocols

### ISSUE THREAD

**Issue by nrc** [pingcap/kvproto#352]
Generate wrapper code which will wrap the code generated by Prost and emulate the API generated by rust-protobuf. The goal is that minimal changes are required by clients to use Prost rather than rust-protobuf.

**Comment by nrc** [comment]
I think this should include creating our own, Prost version of the `Message` trait.

**Comment by Hoverbear** [comment]
@nrc any update on this?

**Comment by ice1000** [comment]
The work has been moved to the protobuf-build repo, so I'd say "it's OK to close this issue"

**Comment by Hoverbear** [comment]
Great!
