### ISSUE TITLE
Installation requires cmake, protoc, golang, perl...

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/kvproto#354]
Prior to https://github.com/pingcap/kvproto/pull/347 I do not think `cmake`, `protoc`, `golang`, `perl` were required to pull `kvproto` into a Rust dependency.

Having these extra dependencies is rather problematic. `protoc` in particular is not a commonly installed tool.

Resolving this issue would involve ensuring downstream dependencies can use `kvproto` without:

* [ ] `cmake`
* [ ] `protoc`
* [ ] `golang`
* [ ] `perl`

Labelling this as a bug as I think it's a regression. cc @nrc .

**Comment by nrc** [comment]
This is addressed in my WIP PR: https://github.com/pingcap/kvproto/pull/349 by making code generation opt-in and not done by default.

**Comment by Hoverbear** [comment]
Thanks Nick! :)

**Comment by ice1000** [comment]
`sed` is also needed by the way.

**Comment by gregwebs** [comment]
@nrc should this issue be closed now? We can open up a new one for further simplifying the build process.

**Comment by nrc** [comment]
Sure, I have no idea about the current build reqs, but this issue is out of date
