### ISSUE TITLE
Does not complete build 

### ISSUE THREAD

**Issue by rustysys-dev** [pingcap/kvproto#589]
kvproto does not compile.. Unfortunately I do not know many specifics about this..  but the below error states that it seems to be an issue with permissions.. 

```
error: failed to run custom build command for `kvproto v0.0.2 (https://github.com/pingcap/kvproto.git#b8bc94dd)`

Caused by:
  process didn't exit successfully: `/home/procyclinsur/test/kvif/target/debug/build/kvproto-af7c9bf33012dd14/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/procyclinsur/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.11.1/src/prost_impl.rs:8:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

any insight on this would be appriciated

**Comment by gregwebs** [comment]
You don't actually need to run `make rust`. The Rust code is generated by library macros used by TiKV.

**Comment by gregwebs** [comment]
You can now build with `./scripts/docker-build.sh` and then `./scripts/docker-run.sh make go rust`

**Comment by rustysys-dev** [comment]
@gregwebs Thanks!! I will try to check this out when I have time (been pretty busy lately)!! I will close this for now with the assumption that all is good!!
