### ISSUE TITLE
Use gogo/protobuf insead of golang/protobuf 

### ISSUE THREAD

**Issue by shenli** [pingcap/kvproto#93]
- [ ] Change proto between TiDB and TiKV
- [ ] Change proto between TiDB and PD

https://github.com/alecthomas/go_serialization_benchmarks
BenchmarkGoprotobufMarshal-8              2000000        746 ns/op      312 B/op        4 allocs/op
BenchmarkGoprotobufUnmarshal-8              2000000        978 ns/op      432 B/op        9 allocs/op
BenchmarkGogoprotobufMarshal-8             10000000        211 ns/op       64 B/op        1 allocs/op
BenchmarkGogoprotobufUnmarshal-8            5000000        289 ns/op       96 B/op        3 allocs/op

**Comment by siddontang** [comment]
We must install gogo first, and then generate rust proto. like:

```
protoc -I.:$GOPATH/src/github.com/gogo/protobuf:$GOPATH/src/github.com/gogo/protobuf/protobuf --rust_out=. *.proto
```

@coocood
